### ISSUE TITLE
Camada de serviço e reutilização de modelos de domínio

### ISSUE THREAD

**Issue by rafaelcanovas** [caiobrian/anima-vita#1]
https://github.com/caiobrian/anima-vita/blob/28730a29473208665d3b9a0138e7953859625abf/src/pages/Home/hooks/useAnimeData.ts#L10-L26

Boa tarde Caio, tudo bem?

Percebi que você escolheu manter parte da funcionalidade da busca de dados da API externa e tradução dos dados em modelos de domínio, dentro da camada de Hooks da página `Home`.

Qual seria sua abordagem caso outra página da aplicação precisasse buscar dados de animes, ou personagens?

Obrigado!

**Comment by caiobrian** [comment]
Boa tarde, Rafael! Tudo bem e com você?

Eu removeria o hooks da página home, criaria uma nova camada de hooks na
src e utilizaria a partir de lá
Também iria dividir o hook original em dois, uma para animes e outro para
personagens.
E moveria as chamadas para API para a camada de services, para que eu
pudesse reaproveitar em outros componentes sem depender dos hooks.



Em seg., 14 de mar. de 2022 às 17:17, Rafael Canovas <
***@***.***> escreveu:

**Comment by rafaelcanovas** [comment]
Obrigado Caio!
